### ISSUE TITLE
Potential (Neglected) incompatibility with Vanilla Genetics Expanded

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/EliteBionicsFramework#48]
From Steam user, which eventually is from Discord:

---

https://gist.github.com/351145e894d52471444ac43492b9a250

https://discord.com/channels/214523379766525963/1050249456043425822

**Comment by Vectorial1024** [comment]
The reason why I mark this as "neglected" is because the entire feature of verb power adjustment is forgotten... Yes this feature exists in the mod, but at some point, I have totally forgotten about it and continued with only HP adjustmnent in my mind.

**Comment by Evonos** [comment]
hey thanks for opening the issue.

Ill copy the text in here ( because the discord thread will get deleted  after a while ) 

https://gist.github.com/351145e894d52471444ac43492b9a250


"EBF.Patches.PostFix_VerbProperties_GetDamageFactorFor.EBF.Patches.PostFix_VerbProperties_GetDamageFactorFor.PostFix_Patch0" is, specifically the EBF part, which is elite bionics framework. The next entry underneath is another patch:
"Verse.VerbProperties.Verse.VerbProperties.GetDamageFactorFor_Patch2"
In the harmony list "GetDamageFactorFor" is mentioned with vanilla genetics
both are being labeled postifx, which is a patch executed after the original method.

**Comment by Vectorial1024** [comment]
Alright, I think I know what this is.

Part of this is because I was not too familiar with the deep details of C#, but when coding this a long time ago, the IDE suggested an auto-fix to the null-value problem to me which (today) turns out to be the wrong suggestion. It literally gave me no errors when compiling...

The update will be released this week.

**Comment by Vectorial1024** [comment]
Update released. Therefore, closing this.
