### ISSUE TITLE
Transpilers approach improvement suggestion

### ISSUE THREAD

**Issue by abel1502** [Vectorial1024/EliteBionicsFramework#72]
The current approach to transpilers, targeting nth `callvirt` instruction, is incredibly prone to silent failures if the target method is ever changed. A much more robust alternative would be to use the following condition:
```C#
instruction.Calls(AccessTools.Method("BodyPartDef:GetMaxHealth", new Type[] { typeof(Pawn) }))
```
as well as introducing a failure check at the end, along the lines of:
```C#
if (!patchComplete)
{
	Log.Error("EBF: Failed to patch PawnCapacityUtility:CalculatePartEfficiency()");
}
```

I won't provide a pull request, since for myself I am implementing those directly in the compiled dll via dnSpy. However, these should be trivial to implement, and should provide significant benefits

**Comment by Vectorial1024** [comment]
I do not understand. From my understanding, I or users will know something is up if the method is changed. Consider:

- some arg type is changed: invalid IL code error (reason: cannot pass type X to type Y)
- arg count is changed: invalid IL code error (reason: too many items on the eval stack or not enough items on the eval stack)
- method name is changed: Harmony failed to patch code (reason: method not found)
- new method overload added: a variant of "arg count is changed"

In practice, because body part HP is so core in the game, code changes are very unlikely. The patches are likely to work with no action needed from my side even if a new game version is released. The problematic part would be mod integration breaking, but that happens rarely as well.

But still, due to recent severe irl problems, modding progress has stalled greatly (not just RimWorld modding, other games as well). I will not be addressing this in high priority. I will however leave this open as some sort of interesting technical research.

**Comment by Vectorial1024** [comment]
PS: if the method is changed as in the inside code is rewritten, then I will have to read the new code to remake my patches anyways. There are no guarantees there would be the same number of method calls, much less the max ldfld number. Being brittle is pretty much intended.

The patch will fail and users (preferrably with error log enabled; also, red errors will always force display the debug log) will see errors on the title screen. Your `Log.Error` approach has no intrinsic differences from the "delegate to Harmony to announce patch failed" method. Knowing that a patch somehow failed plus a relevant stacktrace (currently also contains the patcher's information) is already sufficient for me to start work, further info is unhelpful.

**Comment by Vectorial1024** [comment]
Ah yeah the `CodeMatcher`, I basically forgot about it.

The plan was to eventually change every transpiler to at least use the `CodeMatcher` method, but irl got in the way and I basically forgot about the plan. Now it is half way complete, and there is currently no ETA of completion.

I do hope irl can finally unblock to let me finish things...

---

But still, do you happen to discover which other mod is conflicting with the transpiler? I got random separate reports of Pawnmorpher seemingly not working with EBF and I have not yet started any investigation.

**Comment by abel1502** [comment]
I'm not using pawnmorpher, so it's something else, but I'm not sure what. I can't find the WTP log from the time of the issue, and I can't reproduce it anew since I've already fixed the dll. Sorry(

**Comment by Vectorial1024** [comment]
Ah yeah you can check more transpiler-related progress over here https://github.com/Vectorial1024/EliteBionicsFramework/issues/63

**Comment by Vectorial1024** [comment]
For some added info, this time in the 1.5 compatibility update, one old-style transpiler patch did silently fail and caused a cursed reflection bug. Normally a failed patch will be immediately indicated by a "invalid IL code" exception, but this time it somehow passed through the IL code check and resulted in several variables having unpredictable contents and types in it.

I guess there is a reason to do the new-style transpilation after all.

**Comment by Vectorial1024** [comment]
With CodeMatcher, if the patch failed due to no pattern matched, then it gives "arg out-of-range" exception because the matcher would have already reached the end of the function (pointer now pointing at emptiness) and I would be trying to set the IL code at pointer to become `nop`. Then, I/user will know.

Still, for the CodeMatcher Repeat usage, you may check commit 73b02a296120e3e9434bdca7eb2a55508205dde3 ; it turns out a transpiler patch has to patch the same code several times.

This is finally complete.

**Comment by Vectorial1024** [comment]
Regarding the "silently fail" part, I noticed something.

Must have been a past RimWorld update, but if users do not enable development mode, then even if there are red errors, the debug log will never appear. This makes failed patches silent by virtue of having no one to see them.

Might need to somehow improve the communications.
